# Generated by Django 5.1.1 on 2024-09-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_link',
            field=models.URLField(default=''),
        ),
    ]
